### ISSUE TITLE
Visual Stuido Test Agent do i need it?

### ISSUE THREAD

**Issue by Mastahh** [Microsoft/vstest-docs#159]
Hi,

I'm trying to Migrate Tests from MTM 2012 to TFS 2017 and now I have problem with test run and i'm not sure do i need to have VS Test Agent on PC where i'm going to run UI tests using VsTest.

As I understand I do not need to have it. 

I have error when run tests but i'm not sure why it is

Failed   CodedUITest_2873_Ranorex_tests_will_run (Data Row 0)
Error Message:
   Error calling Initialization method for test class Tests.FM.CodedUITestMain: System.IO.FileNotFoundException: The system cannot find the file specified. (Exception from HRESULT: 0x80070002)
Stack Trace:
    at System.Reflection.RuntimeAssembly.nLoadFile(String path, Evidence evidence)
   at System.Reflection.Assembly.LoadFile(String path)
   at Microsoft.VisualStudio.TestTools.UITest.Framework.UITestExtensionPackageManager.LoadAssembly(String assemblyFile)

**Comment by HeroMaxPower** [comment]
My assumption is that you are trying to run these tests on a TFS 2017 build server. If this is the case you have Ranorex tests that require a Interactive Test Agent, if you are running any tests that are UI based you will need to install a Test Agent with interactive mode enabled onto your test VM with the application that needs to be tested.
