### ISSUE TITLE
Test discovery fails with Guid should contain 32 digits with 4 dashes (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx).

### ISSUE THREAD

**Issue by frjol** [Microsoft/vstest-docs#161]
Hello all,

We are having an issue regarding Native C++ tests discovery in Visual Studio or in command line. It seems to be new in 15.8. Browsing around I could not find any work around or similar issue opened. I managed to build the same release version and could not find an easy way of fixing it. 

> vstest.console.exe "D:\TFS\Synergis\Dev\Integration\Main\Source\bin\Debug\AxisExtension.Native.UnitTests.dll"  /TestAdapterPath:D:\TFS\Synergis\Dev\Integration\Main\Source\bin\Debug  /diag:diag.txt
> Microsoft (R) Test Execution Command Line Tool Version 15.8.0-dev
> Copyright (c) Microsoft Corporation.  All rights reserved.
> 
> Starting test execution, please wait...
> Logging Vstest Diagnostics in file: D:\Code\vstest-rel-15.8\diag.txt
> Data collection : Logging DataCollector Diagnostics in file: D:\Code\vstest-rel-15.8\diag.datacollector.18-10-25_09-18-01_06900_1.txt
> Data collection : Data collector 'UnitTestIsolation' threw an exception during type loading, construction, or initialization: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ArgumentOutOfRangeException: Length cannot be less than zero.
> Parameter name: length
>    at System.String.Substring(Int32 startIndex, Int32 length)
>    at Microsoft.VisualStudio.IntelliTrace.TraceLogger.get_InstallDir() in F:\dd\src\edev\diagnostics\intellitrace\tracelog\TraceLogger.cs:line 1222
>    at Microsoft.VisualStudio.IntelliTrace.TraceLogger.GetProfilerEnvVars() in F:\dd\src\edev\diagnostics\intellitrace\tracelog\TraceLogger.cs:line 937
>    at Microsoft.VisualStudio.TraceCollector.CommonDataCollector..ctor() in F:\dd\src\edev\diagnostics\intellitrace\collectorV2\CommonDataCollector.cs:line 142
>    at Microsoft.VisualStudio.TraceCollector.UnitTestIsolationDataCollector..ctor() in F:\dd\src\edev\diagnostics\intellitrace\collectorV2\UnitTestIsolationCollector\UnitTestIsolationDataCollector.cs:line 35
>    --- End of inner exception stack trace ---
>    at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
>    at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
>    at System.Activator.CreateInstance(Type type, Boolean nonPublic)
>    at System.Activator.CreateInstance(Type type)
>    at Microsoft.VisualStudio.TestPlatform.Common.ExtensionFramework.TestPluginManager.CreateTestExtension[T](Type extensionType) in D:\Code\vstest-rel-15.8\src\Microsoft.TestPlatform.Common\ExtensionFramework\TestPluginManager.cs:line 96
>    at Microsoft.VisualStudio.TestPlatform.Common.ExtensionFramework.Utilities.LazyExtension`2.get_Value() in D:\Code\vstest-rel-15.8\src\Microsoft.TestPlatform.Common\ExtensionFramework\Utilities\LazyExtension.cs:line 153
>    at Microsoft.VisualStudio.TestPlatform.Common.DataCollector.DataCollectionManager.TryGetTestExtension(String extensionUri) in D:\Code\vstest-rel-15.8\src\Microsoft.TestPlatform.Common\DataCollection\DataCollectionManager.cs:line 404
>    at Microsoft.VisualStudio.TestPlatform.Common.DataCollector.DataCollectionManager.LoadAndInitialize(DataCollectorSettings dataCollectorSettings, String settingsXml) in D:\Code\vstest-rel-15.8\src\Microsoft.TestPlatform.Common\DataCollection\DataCollectionManager.cs:line 429.
> Logging TestHost Diagnostics in file: D:\Code\vstest-rel-15.8\diag.host.18-10-25_09-18-01_79093_1.txt
> Guid should contain 32 digits with 4 dashes (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx).
> No test is available in D:\TFS\Synergis\Dev\Integration\Main\Source\bin\Debug\AxisExtension.Native.UnitTests.dll. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.
> 
> Test Run Failed.

We have the same issue just listing the tests. In some cases, it can list a couple tests before failing. We could not find anything wrong in our tests related to that issue. I included diag files.

Thanks,

[diag.host.18-10-25_09-18-01_79093_1.txt](https://github.com/Microsoft/vstest-docs/files/2515016/diag.host.18-10-25_09-18-01_79093_1.txt)
[diag.txt](https://github.com/Microsoft/vstest-docs/files/2515019/diag.txt)
[diag.datacollector.18-10-25_09-18-01_06900_1.txt](https://github.com/Microsoft/vstest-docs/files/2515021/diag.datacollector.18-10-25_09-18-01_06900_1.txt)

**Comment by frjol** [comment]
meant to vstest repo
